server:
  port: 8081

spring:
  application:
    name: song
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:2345/song
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'